CREATE TABLE IF NOT EXISTS favorite_ads(
    id BIGSERIAL PRIMARY KEY,
    ad_id BIGINT   NOT NULL,
    user_id BIGINT   NOT NULL,
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ad_id) REFERENCES ads(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);